serve:
  cookies:
    same_site_mode: Lax

dsn: memory

urls:
  self:
    issuer: http://127.0.0.1:5444
  consent: http://127.0.0.1:3100/consent
  login: http://127.0.0.1:3000/login
  logout: http://127.0.0.1:3000/logout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
